/// A single parsed journal entry from a ServiceNow journal field blob.
///
/// ServiceNow returns journal fields (`comments`, `work_notes`) as a single
/// concatenated text blob via inline queries. This struct represents one
/// parsed entry from that blob.
///
/// # Entry format
///
/// ```text
/// 2026-04-03 14:53:01 - Conor Coleman (Additional Comments (Public))
/// Hi Team,
/// I am unable to find any AD group with name "Lawsn_admin".
/// ```
#[derive(Debug, Clone)]
pub struct JournalEntry {
    /// Timestamp string, e.g. `"2026-04-03 14:53:01"`.
    pub timestamp: String,
    /// Author display name, e.g. `"Conor Coleman"`.
    pub author: String,
    /// Source type, e.g. `"Additional Comments (Public)"` or `"Email"`.
    pub source: String,
    /// The body text of the entry.
    pub body: String,
}

impl JournalEntry {
    /// Returns `true` if this entry was generated by an email notification.
    pub fn is_email(&self) -> bool {
        self.source.contains("Email")
    }
}

/// Parse a ServiceNow journal text blob into individual [`JournalEntry`] values.
///
/// Entries are returned in the same order as the blob (newest first).
///
/// # Examples
///
/// ```
/// use servicenow_rs::model::journal::parse_journal;
///
/// let blob = "2026-04-03 14:53:01 - Conor Coleman (Additional Comments (Public))\n\
///             Hi Team, can you confirm the group name?\n\
///             \n\
///             2026-04-01 09:44:28 - Xin Li (Additional Comments (Public))\n\
///             SAT team please process this request.\n\
///             \n";
///
/// let entries = parse_journal(blob);
/// assert_eq!(entries.len(), 2);
/// assert_eq!(entries[0].author, "Conor Coleman");
/// assert!(entries[0].body.contains("confirm the group name"));
/// assert_eq!(entries[1].author, "Xin Li");
/// ```
pub fn parse_journal(blob: &str) -> Vec<JournalEntry> {
    let mut entries = Vec::new();
    let mut current: Option<(String, String, String, Vec<&str>)> = None;

    for line in blob.lines() {
        if let Some((ts, author, source)) = parse_header(line) {
            if let Some(prev) = current.take() {
                entries.push(finish_entry(prev));
            }
            current = Some((ts, author, source, Vec::new()));
        } else if let Some((_, _, _, ref mut body_lines)) = current {
            body_lines.push(line);
        }
    }
    if let Some(prev) = current {
        entries.push(finish_entry(prev));
    }

    entries
}

fn finish_entry((ts, author, source, body_lines): (String, String, String, Vec<&str>)) -> JournalEntry {
    JournalEntry {
        timestamp: ts,
        author,
        source,
        body: body_lines.join("\n").trim().to_string(),
    }
}

/// Parse a journal entry header line.
///
/// Expected format: `"YYYY-MM-DD HH:MM:SS - Author Name (Source Type (Visibility))"`
fn parse_header(line: &str) -> Option<(String, String, String)> {
    if line.len() < 25 {
        return None;
    }
    let ts = &line[..19];
    // Validate timestamp shape
    if ts.as_bytes().get(4) != Some(&b'-') || ts.as_bytes().get(10) != Some(&b' ') {
        return None;
    }
    if line.get(19..22)? != " - " {
        return None;
    }
    let rest = &line[22..];
    // Use first '(' to split — source type may contain nested parens
    let paren_pos = rest.find('(')?;
    let author = rest[..paren_pos].trim().to_string();
    let source = rest[paren_pos + 1..].strip_suffix(')').unwrap_or(&rest[paren_pos + 1..]).trim().to_string();
    Some((ts.to_string(), author, source))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_single_entry() {
        let blob = "2026-04-03 14:53:01 - Conor Coleman (Additional Comments (Public))\nHello world\n";
        let entries = parse_journal(blob);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].timestamp, "2026-04-03 14:53:01");
        assert_eq!(entries[0].author, "Conor Coleman");
        assert_eq!(entries[0].source, "Additional Comments (Public)");
        assert_eq!(entries[0].body, "Hello world");
    }

    #[test]
    fn test_parse_multiple_entries() {
        let blob = "\
2026-04-03 14:53:01 - Alice (Additional Comments (Public))
First comment

2026-04-01 09:44:28 - Bob (Work notes)
Internal note
";
        let entries = parse_journal(blob);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].author, "Alice");
        assert_eq!(entries[0].body, "First comment");
        assert_eq!(entries[1].author, "Bob");
        assert_eq!(entries[1].source, "Work notes");
    }

    #[test]
    fn test_is_email() {
        let blob = "2026-04-03 10:00:00 - System (Email)\nNotification sent\n";
        let entries = parse_journal(blob);
        assert!(entries[0].is_email());
    }

    #[test]
    fn test_empty_blob() {
        assert!(parse_journal("").is_empty());
        assert!(parse_journal("   \n  ").is_empty());
    }

    #[test]
    fn test_multiline_body() {
        let blob = "2026-04-03 14:53:01 - User (Additional Comments (Public))\nLine 1\nLine 2\nLine 3\n";
        let entries = parse_journal(blob);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].body, "Line 1\nLine 2\nLine 3");
    }
}
